dist: xenial
language: python
python:
  - "3.6"
cache: pip
before_install:
  - pip install -U pip
  - pip install -U pytest
  - pip install -U freezegun==0.3.15
  - pip install -r requirements.txt
install:
  - python setup.py install
script:
  - pytest fp
